[package]
name = "switchblade"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
input = "0.9.0"
libc = "0.2.155"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
